#!/bin/bash
# Build llms-full.txt by concatenating the English documentation set.
#
# llms-full.txt is the single-file companion to llms.txt — it ships the full
# English docs as one Markdown file so LLMs can ingest the entire knowledge
# base in a single pass (see the llms.txt proposal at https://llmstxt.org).
#
# Why English-only:
#   - docs/en/ and docs/zh/ are 1:1 translations; including both would
#     double the byte count without adding new information for an LLM.
#   - The CLI command names, flags, and error messages are themselves
#     English, so anchoring the LLM to the English docs keeps terminology
#     consistent with the actual binary.
#   - Chinese readers are still discoverable via llms.txt, which links to
#     docs/zh/ explicitly.
#
# Re-run this whenever README.md or docs/en/ changes; commit the regenerated
# llms-full.txt alongside the source change. The release checklist points
# back here.
#
# Usage:
#   bash scripts/build-llms-full.sh
#
# Output:
#   ./llms-full.txt at the project root.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

OUTPUT="llms-full.txt"

# Source files in user-learning order: overview → install → auth → tutorial
# → command reference (by usage frequency) → permissions → FAQ.
FILES=(
  "README.md"
  "docs/en/installation.md"
  "docs/en/authentication.md"
  "docs/en/image-workflow.md"
  "docs/en/core.md"
  "docs/en/image.md"
  "docs/en/apikey.md"
  "docs/en/docker.md"
  "docs/en/network.md"
  "docs/en/skills.md"
  "docs/en/ram-permissions.md"
  "docs/en/faq.md"
)

# Fail fast if any input is missing.
for f in "${FILES[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "❌ Missing input: $f" >&2
    exit 1
  fi
done

# Write the preamble.
cat > "$OUTPUT" <<'EOF'
# AgentBay CLI — Full Documentation

> Official command-line interface for Alibaba Cloud AgentBay services. Manages the lifecycle of CodeSpace images, API keys, Docker registry (ACR) operations, skills, and network packages.

This file aggregates the English documentation set into a single Markdown document for LLM ingestion. It is auto-generated by `scripts/build-llms-full.sh` from the canonical sources marked with `# === Source: <path> ===` headers below — refer back to the originals at those paths for the source of truth.

For the navigable index (including Chinese documentation links), see [llms.txt](llms.txt).

EOF

# Append each doc with a Source marker; strip bilingual switcher lines like:
#   [中文版](README.zh-CN.md) | **English**
#   **中文** | [English](README.md)
for f in "${FILES[@]}"; do
  {
    printf '\n---\n\n# === Source: %s ===\n\n' "$f"
    sed -E \
      -e '/^\[[^]]*\]\([^)]+\.md\)[[:space:]]*\|[[:space:]]*\*\*[^*]+\*\*[[:space:]]*$/d' \
      -e '/^\*\*[^*]+\*\*[[:space:]]*\|[[:space:]]*\[[^]]*\]\([^)]+\.md\)[[:space:]]*$/d' \
      "$f"
  } >> "$OUTPUT"
done

# Stats: rough English token estimate is ~4/3 words.
LINES=$(wc -l < "$OUTPUT" | tr -d ' ')
WORDS=$(wc -w < "$OUTPUT" | tr -d ' ')
BYTES=$(wc -c < "$OUTPUT" | tr -d ' ')
TOKENS_EST=$(( WORDS * 4 / 3 ))

echo "✅ Generated $OUTPUT"
echo "   Lines:  $LINES"
echo "   Words:  $WORDS"
echo "   Bytes:  $BYTES"
echo "   Tokens: ~$TOKENS_EST (rough English estimate)"
